version: "3.7"

services:
  db: 
    image: postgres
    container_name: db
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=hospital
      - POSTGRES_DB=ess
    volumes:
      - pgdata:/data/postgres
    network_mode: host
    
  api: 
    build: .
    container_name: api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host
    
volumes:
  pgdata:
    driver: local